name: "Proxy: deploy"

on:
  # Push to the main branch
  push:
    tags:
      - "v*"

jobs:
  # Build and publish the commit to docker
  docker:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'ari-party/growthbook-proxy-bun' }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare build metadata
        id: metadata
        run: |
          # Store current git hash and date in files
          mkdir -p buildinfo
          echo "${GITHUB_SHA}" > buildinfo/SHA
          printf '%(%Y-%m-%dT%H:%M:%SZ)T' > buildinfo/DATE
          echo "docker_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

          # If this is a tag, echo tag to output
          tag=$(git tag --points-at HEAD)
          if [ -n "$tag" ]; then
            echo "tag=robertsspaceindustries/growthbook-proxy-bun:$tag" >> $GITHUB_OUTPUT
          else
            echo "tag=" >> $GITHUB_OUTPUT
          fi

      - name: Build, tag, and push image to Docker Hub
        uses: docker/build-push-action@v6.18.0
        with:
          push: true
          context: .
          tags: |
            robertsspaceindustries/growthbook-proxy-bun:latest
            robertsspaceindustries/growthbook-proxy-bun:git-${{ steps.metadata.outputs.docker_sha }}
            ${{ steps.metadata.outputs.tag }}
          platforms: linux/amd64,linux/arm64
